Repository Homebrew/install, pull requests merged in 2020-11, with the labels that each got.

#348 install: recommend Rosetta only on macOS
  install.sh
Labels: needs response

#346 macOS Big Sur
  install.sh
Labels: do not merge

#341 Use sudo -v instead of sudo -l mkdir
  install.sh
Labels: linux

#358 execute_sudo: Fix when SUDO_ASKPASS without sudo
  install.sh
Labels: bug
