Repository Homebrew/install, pull requests merged in 2020-03, with the labels that each got.

#256 Bash installer
  .github/workflows/tests.yml
  README.md
  install
  install.sh
Labels: do not merge

#267 Linux support for the installer
  .github/workflows/tests.yml
  install.sh
Labels: needs response

#274 Move Linux Next steps after the Next steps heading
  install.sh
Labels: bug

#275 install.sh: Use sudo -l mkdir rather than sudo -v
  install.sh
Labels: bug

#290 Fix terminal device
  install.sh
Labels: bug
